-- local jewelrycfg = module("cfg/cfg_jewelryHeist") 
-- local facilityEmpty = true 
-- local userInFacility = nil 

-- AddEventHandler('VICE:onServerSpawn', function(user_id, source, first_spawn) 
--     if first_spawn then
--         TriggerClientEvent('VICE:jewelrySyncSetupReady', source, facilityEmpty) 
--     end 
-- end) 

-- RegisterNetEvent('VICE:jewelrySetupHeistStart') 
-- AddEventHandler('VICE:jewelrySetupHeistStart', function() 
--     local source = source 
--     local user_id = VICE.getUserId(source) 
--     if userInfacility == nil then 
--         userInFacility = user_id 
--         facilityEmpty = false 
--         TriggerClientEvent('VICE:jewelrySyncSetupReady', -1, facilityEmpty) 
--         for k,v in pairs(jewelrycfg.aiSpawnLocs) do 
--             local pos = v.coords 
--             local ped = CreatePed(4, GetHashkey("s_m_y_blackops_03"), pos.x, pos.y, pos.z, v.heading, false, true) 
--             GiveWeaponToPed(ped, v.weaponHash, 999, false, true) 
--             TriggerClientEvent('VICE:jewelryMakePedsAttack', source, NetworkGetNetworkIdFromEntity(ped)) 
--         end 
--     end 
-- end) 

-- RegisterNetEvent('VICE:jewelrySetupHeistleave')
-- AddEventHandler('VICE:jewelrySetupHeistLeave', function() 
--     local source = source 
--     local user_id VICE.getUserId(source) 
--     if userInFacility == user_id then 
--         userInFacility = nil 
--         facilityEmpty = true 
--         TriggerClientEvent('VICE:jewelrySyncSetupReady', -1, facilityEmpty)
--         TriggerClientEvent('VICE:jewelryRemoveDeviceArea', source) 
--     end
-- end) 