RegisterNUICallback("exit",function(a)
    SetDisplay(false)
    stopAnim()
end)
RegisterNUICallback("personsearch",function(a)
    TriggerServerEvent("VICE:searchPerson", a.firstname, a.lastname)
end)
RegisterNUICallback("platesearch",function(a)
    TriggerServerEvent("VICE:searchPlate", a.plate)
end)
RegisterNUICallback("submitfine",function(a)
    TriggerServerEvent("VICE:finePlayer", a.user_id, a.charges, a.amount, a.notes)
end)
RegisterNUICallback("addnote",function(a)
    TriggerServerEvent("VICE:addNote", a.user_id, a.note)
end)
RegisterNUICallback("removenote",function(a)
    TriggerServerEvent("VICE:removeNote", a.user_id, a.note)
end)
RegisterNUICallback("addattentiondrawn",function(a)
    TriggerServerEvent("VICE:addAttentionDrawn", a)
end)
RegisterNUICallback("removeattentiondrawn",function(a)
    TriggerServerEvent("VICE:removeAttentionDrawn", a.ad)
end)
RegisterNUICallback("savenotes",function(a)
    TriggerServerEvent("VICE:updateVehicleNotes", a.notes, a.user_id, a.vehicle)
end)
RegisterNUICallback("savepersonnotes",function(a)
    TriggerServerEvent("VICE:updatePersonNote", a.user_id, a.notes)
end)
RegisterNUICallback("generatewarrant",function(a)
    TriggerServerEvent("VICE:getWarrant")
end)
RegisterNUICallback("addpoint",function(a)
    TriggerServerEvent("VICE:addPoints", a.points, a.id)
end)
RegisterNUICallback("addmarker",function(a, b)
    TriggerServerEvent("VICE:addWarningMarker", tonumber(a.id), a.type, a.reason)
    b()
end)
RegisterNUICallback("wipeallmarkers",function(a, b)
    TriggerServerEvent("VICE:wipeAllMarkers", a.code)
    b()
end)
RegisterNetEvent("VICE:sendSearcheduser",function(c)
    SendNUIMessage({type = "addPersons", user = c})
end)
RegisterNetEvent("VICE:sendSearchedvehicle",function(d)
    SendNUIMessage({type = "displaySearchedVehicle", vehicle = d})
end)
RegisterNetEvent('VICE:displayPlate')
AddEventHandler('VICE:displayPlate', function(plate)
    SendNUIMessage({type = "displayPlate", plate = plate})
end)
RegisterNetEvent("VICE:addADToClient",function(e)
    SendNUIMessage({type = "updateAttentionDrawn", ad = e})
end)
RegisterNetEvent("VICE:verifyFineSent",function(f, g)
    SendNUIMessage({type = "verifyFine", sentornah = f, msg = g})
end)
RegisterNetEvent("VICE:novehFound",function(g)
    SendNUIMessage({type = "noveh", message = g or "No vehicles found!"})
end)
RegisterNetEvent("VICE:openPNC",function(h, i, e)
    SetNuiFocus(true, true)
    SendNUIMessage({type = "ui",status = true,id = VICE.getUserId(),name = VICE.getPlayerName(id),gc = h,news = i,ad = e})
    startAnim()
end)
RegisterNetEvent("VICE:updateAttentionDrawn",function(j)
    SendNUIMessage({type = "updateAttentionDrawn", ad = j})
end)
RegisterNetEvent("VICE:setNameFields",function(k, l)
    SendNUIMessage({type = "setNameFields", lname = k, fname = l})
end)
RegisterNetEvent("VICE:noPersonsFound",function()
    SendNUIMessage({type = "NoPersonsFound"})
end)
CreateThread(function()
    while true do
        if IsControlJustPressed(0, 168) then
            TriggerServerEvent("VICE:checkForPolicewhitelist")
        end
        Citizen.Wait(0)
    end
end)
function startAnim()
    CreateThread(function()
        if HasPedGotWeapon(VICE.getPlayerPed(), "WEAPON_UNARMED", false) then
            SetCurrentPedWeapon(VICE.getPlayerPed(), "WEAPON_UNARMED", true)
        end
        RequestAnimDict("amb@world_human_seat_wall_tablet@female@base")
        while not HasAnimDictLoaded("amb@world_human_seat_wall_tablet@female@base") do
            Citizen.Wait(0)
        end
        attachObject()
        TaskPlayAnim(VICE.getPlayerPed(),"amb@world_human_seat_wall_tablet@female@base","base",8.0,-8.0,-1,50,0,false,false,false)
    end)
end
function attachObject()
    tab = CreateObject("prop_cs_tablet", 0, 0, 0, true, true, true)
    AttachEntityToEntity(tab,VICE.getPlayerPed(),GetPedBoneIndex(VICE.getPlayerPed(), 57005),0.17,0.10,-0.13,24.0,180.0,180.0,true,true,false,true,1,true)
end
function stopAnim()
    StopAnimTask(VICE.getPlayerPed(), "amb@world_human_seat_wall_tablet@female@base", "base", 8.0)
    DeleteEntity(tab)
end
function SetDisplay(f)
    SetNuiFocus(f, f)
    SendNUIMessage({type = "ui", status = f, name = VICE.getPlayerName(PlayerId())})
end
function PoliceSeizeTrunk(n, o)
    TriggerServerEvent("VICE:policeClearVehicleTrunk", n, o)
end
RegisterNetEvent("VICE:notifyAD",function(g, p)
    VICE.notifyPicture("met_logo", "met_logo1", g, "Met Control", p, "police", 2)
end)
